### ISSUE TITLE
CORS issue: Mock data unreachable from outside fajarconsultant.com

### ISSUE THREAD

**Issue by jbrokamp** [ahmadfajar/vue-mdbootstrap#3]
Hi Ahmad,

I was trying the `Grid` component > `Overview` example from your website in my local application and wasn't able to load the data from https://vue-mdbootstrap.fajarconsultant.com/data/deserts.json. It looks like a CORS issue, your website is a bit too strict so it's impossible to load the data from any other domain than fajarconsultant.com.

NB: It also breaks your examples on jsfiddle.net.

**Comment by ahmadfajar** [comment]
Thanks for the reminder. I already fix the issue on the server. You can test the examples on jsfiddle.net.
