### ISSUE TITLE
Grid header and content height difference on mobile

### ISSUE THREAD

**Issue by ZarZaKos** [ahmadfajar/vue-mdbootstrap#6]
On mobile the grid header and the grid content has different height.

I fixed it making the th and td tags 3em height, but I guess it's not the best practice.

Thanks for the collection, loved it!
![imagen_2021-03-28_162529](https://user-images.githubusercontent.com/38825494/112765146-3638b900-8fe2-11eb-981c-c7767dac2fb9.png)

**Comment by ahmadfajar** [comment]
Fixed on release version 2.0.4
